### ISSUE TITLE
free周り

### ISSUE THREAD

**Issue by oonisidesu** [oonisidesu/cub3D#27]
エラーケース一通り試してsegv等しないか確認する

**Comment by yu-432** [comment]
src/game/game_handler.c/exit_program関数でexitとreturnが呼ばれている場所があるのでreturnを削除する。

**Comment by yu-432** [comment]
map/okの場合、すべての変数に値が代入されるため問題にはならなかったが、errorの場合に早期にprint_error_exitを呼ぶと初期化されていない変数にアクセスしてしまい、valgrindで警告がでる。

対策として、init_game関数ですべての構造体を初期化する。

**Comment by yu-432** [comment]
マップを読み込んでいる最中に、エラーが見つかった場合に、gnlで確保したstatic領域のメモリがfreeされていない。
`still reachable: 145 bytes in 2 blocks`

**Comment by oonisidesu** [comment]
## gnl
まさかのすいません。。。
1のget_c方式のgnlに変更するでいいと思います

## init_game関数ですべての構造体を初期化する
はい、良いと思います
 init_texture関数はparseで構造体に入れた後に構造体を参照してtextureをmlxで読んでいるのでそこは注意が必要です

**Comment by yu-432** [comment]
t_gameにfd,およびlineを持たせ、print_error_free_exit関数ですべてfree及びcloseできるように変更した。
ダブルフリーを防ぐためwrap_freeの作成
ダブルクローズを防ぐたwrap_closeの作成
