### ISSUE TITLE
game set_player_position

### ISSUE THREAD

**Issue by yu-432** [oonisidesu/cub3D#67]
main.cでset_player_positionという関数を呼び、その関数の内部でfind_player_start_position関数を実行している。

map validate部分でプレイヤーのスタート地点の個数をカウントしエラー処理しているため、この部分でエラーがでるとは考えにくい。そのため、
`
main.c -> set_player_position -> find_player_start_position
`
から
`
main.c -> set_player_position(find_player_start_positionと同様のコード)
`
と階層を浅くしてもいいと感じる。

**Comment by oonisidesu** [comment]
ご確認ありがとうございます。
エラー処理せず、階層浅くした方がわかりやすいですね。
norminetteに引っかからないように修正可能であれば是非お願いしたいです。
