### ISSUE TITLE
parser parse_color_line簡略化

### ISSUE THREAD

**Issue by yu-432** [oonisidesu/cub3D#68]
parse_comma関数でcolor_index(色情報の数、rgbのため3つ以上)のチェックをしているが、この関数をくくっているwhileloopがcolor_index < 3の条件(index2まで)で回っているため、2より大きくならない。
`
if (!parse_color_value(&line, &color[color_index]))
	return (false);
if (!parse_comma(&line, color_index))
	return (false);
color_index++;
`

を

`
if (!parse_color_value(&line, &color[color_index]))
	return (false);
if (*line == ',')
	line++;
color_index++;
`
で問題ないと感じる。

色情報が記載されているlineに余分なものを受け付けないようにするため、
`
while (*line == ' ')
	line++;
`
この部分を削除したほうがいい？

parse_color_value関数内部の
`
while (ft_isdigit(**line))
	(*line)++;
`
この部分はいらない、、？と感じた。

**Comment by oonisidesu** [comment]
ご確認ありがとうございます
修正をお願いしたいです。

### parse_comma関数について
color_indexを条件とするif文が多いですね
ご指摘通りの変更でいいと思います
`
if (!parse_color_value(&line, &color[color_index])) return (false); if (*line == ',') line++; color_index++;
`

### 色情報のバリデートについて
現在、以下の色情報1行の右側のスペースが存在している場合、スペースを無視して画面を表示してしまう
```
F 185,107,47(space)
C 30,144,255
```
ご指摘通り
色情報以外（スペース等）が混ざっている場合はcubファイルエラーとして画面を表示しない方向でいきたいです
以下、削除でお願いします
`
while (*line == ' ') line++;
`

### parse_color_value関数について
ご指摘通り
以下は全く意味がないので削除したいです
`
while (ft_isdigit(**line)) (*line)++;
`

### 追加のお願い
マジックナンバーが多めなのでマクロで管理する修正も余裕があればお願いしたいです

**Comment by yu-432** [comment]
## 色情報のバリデートについて
`F 185,107,47(space)
C 30,144,255`

このようにスペースが混じっている場合、以下の関数で後ろ側についているスペース除去しているためエラーにならず実行されていると考えます。
エラーとして出す場合は、この関数を変更する必要があると思います。
parse_cub_file -> process_file_lines -> read_and_trim_line -> 	ft_strtrim_r
