### ISSUE TITLE
print_error_free_exit

### ISSUE THREAD

**Issue by yu-432** [oonisidesu/cub3D#69]
現状
`
print_error_free_exit -> print_error_free -> print_error -> write関数
`
と階層が深くなっているので、浅くしたほうがコードを追う回数が減って読みやすくなると思う。
読みやすさの問題であることと、freeあたりは最後に作成すればいいと思うため、優先度はめちゃくちゃ低いです。

**Comment by oonisidesu** [comment]
ご確認ありがとうございます

- エラーを出力する関数（print_error）
- freeしてエラーを出力する関数（print_error_free）
- freeしてエラーを出力してexitする関数（print_error_free_exit）

関数として独立させていても問題ないかなと思っています
（ライブラリのような感覚で作成しています）
本来はエラーが出たら即exitせずにまとめてエラーハンドリングしたいなと考えていたためfreeしてエラーを出力する関数が存在してしまっています
