### ISSUE TITLE
テストケースのファイル名変更

### ISSUE THREAD

**Issue by oonisidesu** [oonisidesu/cub3D#71]
どういったテストを行なっているのかがわかるファイル名に変更したい
全部大文字に統一したい

**Comment by yu-432** [comment]
- [ ] 1行だけ0が1000個くらい連続した場合のerror caseを追加作成する
- [ ] ok case name change
- [ ] error case name change
- [ ] bash scriptに無効なfile pathをテストできるコードを追加する
