### ISSUE TITLE
禁止関数のチェック

### ISSUE THREAD

**Issue by oonisidesu** [oonisidesu/cub3D#72]
コードに禁止関数入っていないかチェック

**Comment by yu-432** [comment]
cubファイルが存在しない時の挙動合わせ
-> bzeroを実行した際にt_parseのfdが0になっているので、FD_CLOSEDに変更する

**Comment by yu-432** [comment]
`nm -u obj/**/*.o | grep U | sort | uniq`

上記のコマンドでオブジェクトファイルから使用された関数をすべて出力できる。
